AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template to create the AWS stacks needed for CDM2

Parameters:
  ApplicationName:
    Type: String
    Default: cdm2
    Description: Application name used across all stacks

  Environment:
    Type: String
    AllowedValues:
      - sandbox
      - dev
      - test
      - prod
      - sszweda
    Description: The environment tag is used to designate the Environment Stage of the associated AWS resource.

  sfStorageAWSIAMUserARN:
    Type: String
    Description: "STORAGE_AWS_IAM_USER_ARN from Snowflake"
    Default: "arn:aws:iam::407453656878:user/wdvj-s-iest4729"

  sfStorageAWSExternalID:
    Type: String
    Description: "STORAGE_AWS_EXTERNAL_ID from Snowflake (leave as '000' if Snowflake objects do not exist yet)"
    Default: "000"

  sfSQSChannel:
    Type: String
    Description: "ARN of the SQS channel from Snowflake (leave blank if Snowflake objects do not exist yet)"
    Default: ""

  DeploySnowflakeIntegrationStack:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Description: Whether to deploy Snowflake S3 Integration Job stack


Conditions:
  SallDeployCDM2BucketStack: !Equals [!Ref DeploySnowflakeIntegrationStack, 'true']
  SallDeploySnowflakeIntegrationStack: !Equals [!Ref DeploySnowflakeIntegrationStack, 'true']


Resources:
  CDM2BucketStack:
      Type: "AWS::CloudFormation::Stack"
      Condition: SallDeployCDM2BucketStack
      Properties:
        Parameters:
          Environment: !Ref Environment
          BucketName: "cdm2"
          NotificationPrefix: "input/recon/"
          NotificationSQSQueueARN: !Ref sfSQSChannel
        TemplateURL: !Sub "https://s3.amazonaws.com/${ApplicationName}-cicd-templates-${Environment}/resources/s3-bucket.yml"

  SnowflakeIntegrationStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: SallDeploySnowflakeIntegrationStack
    Properties:
      Parameters:
        Environment: !Ref Environment
        sfStorageAWSIAMUserARN: !Ref sfStorageAWSIAMUserARN
        sfStorageAWSExternalID: !Ref sfStorageAWSExternalID
      TemplateURL: !Sub "https://s3.amazonaws.com/${ApplicationName}-cicd-templates-${Environment}/snowflake-s3-integration/snowflake-integration-stack.yml"
