AWSTemplateFormatVersion: 2010-09-09
Description: Master stack for the CDM2 project

Parameters:
  ApplicationName:
    Type: String
    Default: cdm2
    Description: Application name used across all stacks

  Environment:
    Type: String
    AllowedValues:
      - sandbox
      - dev
      - test
      - prod
      - sszweda
    Description: The environment tag is used to designate the Environment Stage of the associated AWS resource.

  DeploySnowflakeIntegrationStack:
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Description: Whether to deploy Snowflake S3 Integration Job stack

  SnowflakeIAMUserARN:
    Type: String
    Description: "STORAGE_AWS_IAM_USER_ARN from Snowflake"
    Default: "arn:aws:iam::407453656878:user/wdvj-s-iest4729"

  SnowflakeExternalID:
    Type: String
    Description: "STORAGE_AWS_EXTERNAL_ID from Snowflake (leave as '000' if Snowflake objects do not exist yet)"
    Default: "000"

  SnowflakeSQSChannelARN:
    Type: String
    Description: "ARN of the SQS channel from Snowflake (leave blank if Snowflake objects do not exist yet)"
    Default: ""


Mappings:
  BucketDeletionPolicyMap:
    sandbox:
      DeletionPolicy: 'Delete'
    dev:
      DeletionPolicy: 'Delete'
    test:
      DeletionPolicy: 'Retain'
    prod:
      DeletionPolicy: 'Retain'
    sszweda:
      DeletionPolicy: 'Delete'


Conditions:
  SallDeployStorageStack: !Equals [!Ref DeploySnowflakeIntegrationStack, 'true']
  SallDeployPolicyStack: !Equals [!Ref DeploySnowflakeIntegrationStack, 'true']
  SallDeployIAMStack: !Equals [!Ref DeploySnowflakeIntegrationStack, 'true']


Resources:
  StorageStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: SallDeployStorageStack
    Properties:
      Parameters:
        ApplicationName: !Ref ApplicationName
        DeletionPolicy: !FindInMap [BucketDeletionPolicyMap, !Ref Environment, DeletionPolicy]
        Environment: !Ref Environment
        SnowflakeSQSChannelARN: !Ref SnowflakeSQSChannelARN
      TemplateURL: !Sub "https://s3.amazonaws.com/${ApplicationName}-cicd-templates-${AWS::Region}-${Environment}/stacks/storage-stack.yml"

  IAMStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: SallDeployIAMStack
    Properties:
      Parameters:
        ApplicationName: !Ref ApplicationName
        Environment: !Ref Environment
        CDM2BucketName:
          Fn::GetAtt:
          - StorageStack
          - Outputs.CDM2BucketName
        DeploySnowflakeIntegrationStack: !Ref DeploySnowflakeIntegrationStack
        SnowflakeIAMUserARN: !Ref SnowflakeIAMUserARN
        SnowflakeExternalID: !Ref SnowflakeExternalID
      TemplateURL: !Sub "https://s3.amazonaws.com/${ApplicationName}-cicd-templates-${AWS::Region}-${Environment}/stacks/iam-stack.yml"

  PolicyStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: SallDeployPolicyStack
    Properties:
      Parameters:
        Environment: !Ref Environment
        CDM2BucketName:
          Fn::GetAtt:
          - StorageStack
          - Outputs.CDM2BucketName
        DeploySnowflakeIntegrationStack: !Ref DeploySnowflakeIntegrationStack
        SnowflakeS3AccessRoleARN:
          Fn::GetAtt:
          - IAMStack
          - Outputs.SnowflakeS3AccessRoleARN
      TemplateURL: !Sub "https://s3.amazonaws.com/${ApplicationName}-cicd-templates-${AWS::Region}-${Environment}/stacks/policy-stack.yml"
