AWSTemplateFormatVersion: "2010-09-09"

Description: CodePipeline resources for the CDM2 project

Parameters:
  ApplicationName:
    Type: String
    Default: cdm2
    Description: Application name used across all stacks

  Environment:
    Type: String
    AllowedValues:
      - sandbox
      - dev
      - test
      - prod
    Description: The environment tag is used to designate the Environment Stage of the associated AWS resource.

  CodePipelineRoleArn:
    Type: String

  GithubBranchName:
    Type: String

  GithubOrganisationName:
    Type: String

  GithubRepoName:
    Type: String

  SecretStoreName:
    Type: String

Resources:
  CloudFormationPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Sub "${ApplicationName}-cicd-artifacts-${Environment}"
      Name: !Sub "${ApplicationName}-cicd-pipeline-${Environment}"
      RoleArn: !Ref CodePipelineRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: cdm2Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Branch: !Ref GithubBranchName
                OAuthToken: !Sub "{{resolve:secretsmanager:${SecretStoreName}:SecretString:token}}"
                Owner: !Ref GithubOrganisationName
                PollForSourceChanges: true
                Repo: !Ref GithubRepoName
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_AUTO_EXPAND,CAPABILITY_IAM,CAPABILITY_NAMED_IAM
                ChangeSetName: update-stack
                RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/AWSCloudFormationServiceRole"
                StackName: !Sub "${ApplicationName}-masterstack-${Environment}"
                TemplateConfiguration: !Sub "SourceArtifact::${Environment}.json"
                TemplatePath: "SourceArtifact::master-stack.yml"
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
            - Name: Execute
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: update-stack
                StackName: !Sub "${ApplicationName}-masterstack-${Environment}"
              RunOrder: 2

Outputs:
  CodePipelineName:
    Description: CodePipeline Name
    Value: !Ref CloudFormationPipeline
